import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./providers";
import Layout from "@/components/Layout";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <nav className="bg-white bg-opacity-10 backdrop-blur-md text-white p-4 flex justify-center space-x-4 z-10 fixed w-full">
            <Link href="/" className="hover:underline">
              Hyperspace Gates
            </Link>
            <Link href="/journey-cost" className="hover:underline">
              Journey Cost
            </Link>
            <Link href="/route-finder" className="hover:underline">
              Route Finder
            </Link>
          </nav>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
